repos:
-   repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format .
        require_serial: true
        language: system
        types: [ python ]
      - id: ruff
        name: ruff
        entry: uv run ruff check .
        require_serial: true
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: uv run mypy .
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false