name: Code Quality

on:
  schedule:
    - cron: '0 12 * * 1'  # Weekly on Mondays at 12:00 UTC
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --extra dev

    - name: Run pre-commit hooks
      run: uv run pre-commit run --all-files

  quality:
    runs-on: ubuntu-latest
    needs: pre-commit

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --extra dev

    - name: Security check with bandit
      run: uv run bandit -r src/ -f json -o bandit-report.json || true

    - name: Check dependencies with safety
      run: uv run safety check --output json > safety-report.json || true

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json